path: 
  input_path: '/home/arbolitos7/Documents/ArbolitosMiCasita/CrescencioEnLaCiudad/archivos/Zvuk_Dataset/zvuk-interactions.parquet'

schema_config: 
  #Primera carga, luego inmutables
  #Si no se define por defecto es lower
  column_naming: 'lower'
  #Si no se define por defecto es tipo Datetime
  # True si se quieren los string de fecha a tiempo,False para lo contrario 
  # Este, solo ser√° valido a primera carga
  date_format: True
  # Los tipos nativos, se definen en la primera carga
  # Definir tipo de datos en caso de ser necesario 
  # (UNICAMENTE VALIDO A PRIMERA CARGA DE DATOS)
  data_type: 
  # Si no se define por defecto son 2 decimales
  decimal_precision: 3

validation_data:
    sample_size: 0.01
