read_n_rows_sample: 
  n_rows_sample: 1000

general_margin: 
  os_margin: 0.3

default_parquet_factors: 
  parquet_overhead_factor: 1.7

default_csv_factors:
  csv_overhead: 1.8
  csv_bytes_factor: 16

